# Generated by Django 3.1.5 on 2022-10-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20221014_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image3',
            new_name='image3',
        ),
    ]
